version: '3'

tasks:
  serve: dart_frog dev
  build: dart_frog build
  deploy: |
    gcloud run deploy gde-frog \
    --source build \
    --project=lukes-twitch \
    --region=us-east1 \
    --allow-unauthenticated
